Default:
    WorkflowStatus:
      - Value: 'NEW'
        Comparison: EQUALS
    RecordState:
      - Value: 'ACTIVE'
        Comparison: EQUALS
    ProductName:
      - Value: 'Security Hub'
        Comparison: EQUALS